version: "3.0"
services:
    movie-plan-sql:
        image: mysql:8
        container_name: movie-plan-sql
        networks:
            - movie-plan-net
        ports:
            - "3301:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=movieplan-pswd
            - MYSQL_DATABASE=mymovieplan
        volumes:
            - ../data:/var/lib/mysql:rw
    movie-plan-java:
        image: movie-plan-java
        container_name: movie-plan-java
        ports:
            - "8383:8383"
        networks:
            - movie-plan-net
    movie-plan-angular:
        image: movie-plan-angular
        container_name: movie-plan-angular
        ports:
            - "4200:80"
        networks:
            - movie-plan-net
networks:
    movie-plan-net: